config/routes.rb
Rails.application.routes.draw do

  get 'jobs/index'
  get 'jobs/show'
  get 'jobs/new'
  get 'jobs/create'
  get 'jobs/edit'
  get 'jobs/update'
  get 'jobs/destroy'
  get 'projects/index'
  get 'projects/show'
  get 'projects/new'
  get 'projects/create'
  get 'projects/edit'
  get 'projects/update'
  get 'projects/destroy'
  get 'companies/index'
  get 'companies/show'
  get 'companies/new'
  get 'companies/create'
  get 'companies/edit'
  get 'companies/update'
  get 'companies/destroy'
  get 'home/index'
  get 'home/show'

  root :to => "jobs#index"

  match '/index.csv' => 'jobs#index', via: :get, defaults: { format: :csv }

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations'}

  devise_scope :user do
    get "login", to: "users/sessions#new"
    authenticated :user do
      root :to => 'jobs#index', as: :authenticated_root
      get "sign_uo", to: "devise/registrastions#new"
    end
    unauthenticated :user do
      root :to => 'users/sessions#new', as: :unauthenticated_root
    end

  resources :companies
  resources :projects
  resources :jobs

  end

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  require 'csv'

  def index
    @page_title = "Vremenska lista"
    @jobs = Job.all

    @jobs_grid = initialize_grid(@jobs, name: 'jobs', :include => [:user, {project: :company}], order: 'jobs.created_at', order_direction: 'desc',
                                 enable_export_to_csv: true, csv_file_name: "Vremenska")

    export_grid_if_requested
  end

  def show
    @job = Job.find(params[:id])
    @page_title = "Vremenska lista | " + @job.project.title
  end

  def new
    @job = Job.new
    @page_title = "Vremenska lista | New"
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user
    @job.save

    flash[:notice] = "Dodan je novi unos u Vremensku listu!"

    redirect_to jobs_index_path
  end

  def edit
    @job = Job.find(params[:id])
    @page_title = "Edit | "+@job.project.title
  end

  def update
    @job = Job.find(params[:id])

    @job.update(job_params)

    flash[:notice] = "Vremenska lista je izmijenjen!"

    redirect_to jobs_index_path
  end

  def destroy
    @job = Job.find(params[:id])

    @job.destroy

    flash[:notice] = "Unos u Vremenskj listi je izbrisan!"

    redirect_to jobs_index_path
  end

  protected
  def job_params
    params.require(:job).permit(:project_id,:hours, :description, :user_id, :job_date)
  end
end

app/helpers/users/jobs_helper.rb
module Users::JobsHelper
end

app/views/jobs/_jobs_grid.erb
<%= grid(@jobs_grid, show_filters: :always) do |g|

  g.column name: 'Id', attribute: 'id', filter: false, in_csv: false do |t|
    t.id
  end

  g.column name: 'Naziv projekta', attribute: 'title', assoc: :project, custom_filter: :auto do |t|
    t.project.title
  end

  g.column name: 'Klijent', attribute: 'company_id', assoc: :project, custom_filter: Company.all.map{|pr| [pr.name, pr.id]} do |t|
    t.project.company.name
  end

  g.column name: 'Utrošeno sati', attribute: 'hours' do |t|
    t.hours.strftime("%H:%M")
  end

  g.column name: 'Opis', attribute: 'description', in_html: false do |t|
    t.description
  end

  g.column name: 'Datum odrađenog posla', attribute: 'job_date' do |t|
    if t.job_date
      t.job_date.strftime("%d.%m.%Y.")
    end
  end

  g.column name: 'Datum Unosa u listu', attribute: 'created_at', filter: :jquery_datepicker, in_csv: false do |t|
    t.created_at.strftime("%d.%m.%Y. %H:%M")
  end

  g.column name: 'Radnik', attribute: 'id', custom_filter: User.all.map{|user| [user.name+" "+user.surname, user.id]}, assoc: :user do |t|
    t.user.name+" "+t.user.surname
  end

  g.column in_csv: false do |t|
    link_to("Pregled", jobs_show_path(id: t.id))+" / "+link_to("Uredi", jobs_edit_path(id: t.id), :method => :get)
  end

end -%>

app/views/jobs/create.html.erb
<h1>Users::Jobs#create</h1>
<p>Find me in app/views/users/jobs/create.html.erb</p>

app/views/jobs/destroy.html.erb
<h1>Users::Jobs#destroy</h1>
<p>Find me in app/views/users/jobs/destroy.html.erb</p>

app/views/jobs/edit.html.erb
<div class="page-header head-page">
  <h1>Uredi unos u vremenskoj listi</h1>
</div>

<%= simple_form_for @job, html: {class: 'form-horizontal'} do |f| %>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <%= f.input :project_id, label: "Projekt", :as => :select, required: true, :collection => Project.all.map {|kupac| [kupac.title, kupac.id]} %>
        <div class="row">
          <div class="col-md-4">
            <%= f.input :job_date,label: "Datum odrađenog posla", input_html: {value: f.object.job_date.nil? ? Date.today : f.object.job_date, class:"datepicker"},required: true %>
          </div>
          <div class="col-md-4">
            <%= f.input :hours, label: "Utrošeno vrijeme", required: true, default: Time.parse('00:00'),input_html: {value: Time.parse('00:00')}  %>
          </div>
        </div>
        <%= f.input :description, label: "Opis", required: true %>


    <%= f.button :submit, "Izmijeni unos", class: "btn btn-success" %>
    <%= link_to "Cancel", jobs_index_path, class: "btn btn-default" %>
      </div>
    </div>
<% end %>

app/views/jobs/index.html.erb
<div class="page-header head-page">
  <h1>Vremenska lista</h1>
</div>

<%= link_to "Novi unos u listu", jobs_new_path, class: "btn btn-success marginBott" %>

<%= render partial: 'jobs/jobs_grid' %>

app/views/jobs/new.html.erb
<div class="page-header head-page">
  <h1>Kreiraj novi unos u vremensku listu</h1>
</div>

<%= simple_form_for @job, html: {class: 'form-horizontal'} do |f| %>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
    <%= f.input :project_id, label: "Projekt", :as => :select, required: true, :collection => Project.all.map {|kupac| [kupac.title, kupac.id]} %>
    <div class="row">
      <div class="col-md-4">
      <%= f.input :job_date, label: "Datum odrađenog posla", input_html: {value: Date.today, class: "datepicker"},required: true %>
      </div>
      <div class="col-md-4">
      <%= f.input :hours, label: "Utrošeno vrijeme", required: true, default: Time.parse('00:00'),input_html: {value: Time.parse('00:00')}  %>
      </div>
    </div>
    <%= f.input :description, label: "Opis", required: true %>

    <%= f.button :submit, "Kreiraj unos", class: "btn btn-success" %>
    <%= link_to "Cancel", jobs_index_path, class: "btn btn-default" %>
      </div>
    </div>
<% end %>

app/views/jobs/show.html.erb
<div class="page-header head-page">
  <h1><%= link_to @job.project.title, projects_show_path(id: @job.project.id) %> <small><%= @job.job_date.strftime("%d.%m.%Y.") %></small></h1>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <ul class="list-group">
      <li class="list-group-item">
        <span class="badge"><%= @job.hours.strftime("%H:%M").to_s %></span>
        <%= @job.description %>
      </li>
    </ul>
  </div>
</div>

app/views/jobs/update.html.erb
<h1>Users::Jobs#update</h1>
<p>Find me in app/views/users/jobs/update.html.erb</p>