config/routes.rb
Rails.application.routes.draw do

  get 'jobs/index'
  get 'jobs/show'
  get 'jobs/new'
  get 'jobs/create'
  get 'jobs/edit'
  get 'jobs/update'
  get 'jobs/destroy'
  get 'projects/index'
  get 'projects/show'
  get 'projects/new'
  get 'projects/create'
  get 'projects/edit'
  get 'projects/update'
  get 'projects/destroy'
  get 'companies/index'
  get 'companies/show'
  get 'companies/new'
  get 'companies/create'
  get 'companies/edit'
  get 'companies/update'
  get 'companies/destroy'
  get 'home/index'
  get 'home/show'

  root :to => "jobs#index"

  match '/index.csv' => 'jobs#index', via: :get, defaults: { format: :csv }

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations'}

  devise_scope :user do
    get "login", to: "users/sessions#new"
    authenticated :user do
      root :to => 'jobs#index', as: :authenticated_root
      get "sign_uo", to: "devise/registrastions#new"
    end
    unauthenticated :user do
      root :to => 'users/sessions#new', as: :unauthenticated_root
    end

  resources :companies
  resources :projects
  resources :jobs

  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :jobs
  belongs_to :company
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @page_title = "Posao"
    @projects = Project.all

    @projects_grid = initialize_grid(@projects, :include => :company ,order: 'projects.created_at', order_direction: 'desc', per_page: 15)

  end

  def show
    @project = Project.find(params[:id])
    @page_title = "Posao | " + @project.title

    @project_grid = initialize_grid(@project.jobs, :include => :user , order: 'jobs.created_at', order_direction: 'desc', per_page: 15,
                                    name: 'project',enable_export_to_csv: true, csv_file_name: "Vremenska lista")

    export_grid_if_requested
  end

  def new
    @project = Project.new
    @page_title = "Posao | New"
  end

  def create
    @project = Project.new(project_params)

    @project.save

    flash[:notice] = "Dodan je novi posao!"

    redirect_to projects_index_path
  end

  def edit
    @project = Project.find(params[:id])
    @page_title = "Edit | "+@project.title
  end

  def update
    @project = Project.find(params[:id])

    @project.update(project_params)

    flash[:notice] = "Posao je izmijenjen!"

    redirect_to projects_index_path
  end

  def destroy
    @project = Project.find(params[:id])

    @project.destroy

    flash[:notice] = "Posao je izbrisan!"

    redirect_to projects_index_path
  end

  protected
  def project_params
    params.require(:project).permit(:title, :description, :company_id)
  end
end

app/helpers/users/projects_helper.rb
module Users::ProjectsHelper
end

app/views/projects/_project_grid.erb
<%= grid(@project_grid, show_filters: :always) do |g|

  g.column name: 'Id', attribute: 'id', filter: false, in_csv: false do |t|
    t.id
  end

  g.column name: 'Utrošeno sati', attribute: 'hours' do |t|
    t.hours.strftime("%H:%M")
  end

  g.column name: 'Opis', attribute: 'description', in_html: false do |t|
    t.description
  end

  g.column name: 'Datum', attribute: 'created_at', filter: :jquery_datepicker do |t|
    t.created_at.strftime("%d.%m.%Y. %H:%M")
  end

  g.column name: 'Radnik', attribute: 'id', custom_filter: User.all.map{|user| [user.name+" "+user.surname, user.id]}, assoc: :user do |t|
    t.user.name+" "+t.user.surname
  end

  g.column in_csv: false do |t|
    link_to("Pregled", jobs_show_path(id: t.id))+" / "+link_to("Uredi", jobs_edit_path(id: t.id), :method => :get)
  end

end -%>

app/views/projects/_projects_grid.erb
<%= grid(@projects_grid, show_filters: :always) do |g|

  g.column name: 'Id', attribute: 'id', filter: false, in_csv: false do |t|
    t.id
  end

  g.column name: 'Naziv projekta', attribute: 'title' do |t|
    t.title
  end

  g.column name: 'Kompanija', attribute: 'name', custom_filter: :auto, assoc: :company do |t|
    t.company.name
  end

  g.column name: 'Kreiran', attribute: 'created_at', filter: :jquery_datepicker do |t|
    t.created_at.strftime("%d.%m.%Y.")
  end

  g.column name: 'Izmijenjen', attribute: 'updated_at', filter: :jquery_datepicker do |t|
    t.updated_at.strftime("%d.%m.%Y.")
  end

  g.column in_csv: false do |t|
    link_to("Pregled", projects_show_path(id: t.id))+" / "+link_to("Uredi", projects_edit_path(id: t.id), :method => :get)
  end

end -%>

app/views/projects/create.html.erb
<h1>Users::Projects#create</h1>
<p>Find me in app/views/users/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Users::Projects#destroy</h1>
<p>Find me in app/views/users/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<div class="page-header head-page">
  <h1>Uredi Projekt</h1>
</div>

<%= simple_form_for @project, html: {class: 'form-horizontal'} do |f| %>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
    <%= f.input :title, label: "Naziv projekta", required: true %>
    <%= f.input :description, label: "Opis posla", required: true %>
    <%= f.input :company_id, label: "Kupac", required: true, :collection => Company.all.map {|kupac| [kupac.name, kupac.id]}  %>

    <%= f.button :submit, "Izmijeni projekt", class: "btn btn-success" %>
    <%= link_to "Cancel", projects_index_path, class: "btn btn-default" %>
        </div>
      </div>
<% end %>

app/views/projects/index.html.erb
<div class="page-header head-page">
  <h1>Projekti</h1>
</div>

<%= link_to "Novi projekt", projects_new_path, class: "btn btn-success marginBott" %>

<%= render partial: 'projects/projects_grid' %>

app/views/projects/new.html.erb
<div class="page-header head-page">
  <h1>Novi Projekt</h1>
</div>

<%= simple_form_for @project, html: {class: 'form-horizontal'} do |f| %>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
      <%= f.input :title, label: "Naziv projekta", required: true %>
      <%= f.input :company_id, :as => :select, label: "Kupac", required: true, :collection => Company.all.map {|kupac| [kupac.name, kupac.id]} %>
      <%= f.input :description, label: "Opis posla", required: true %>

    <%= f.button :submit, "Kreiraj projekt", class: "btn btn-success" %>
    <%= link_to "Cancel", projects_index_path, class: "btn btn-default" %>
      </div>
    </div>

<% end %>

app/views/projects/show.html.erb
<div class="page-header head-page">
  <h1><%= @project.title %> <small><%= @project.company.name %></small></h1>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
<ul class="list-group">
  <li class="list-group-item"><h3>Kupac: </h3><%= @project.company.name %></li>
  <li class="list-group-item"><h3>Opis projekta: </h3><%= @project.description %></li>
  <li class="list-group-item"><h3>Projekt kreiran: </h3><%= @project.created_at.strftime("%d.%m.%Y.") %></li>
</ul>
  </div>
</div>
<hr>
<%= render partial: 'projects/project_grid' %>

app/views/projects/update.html.erb
<h1>Users::Projects#update</h1>
<p>Find me in app/views/users/projects/update.html.erb</p>