config/routes.rb
Rails.application.routes.draw do

  get 'jobs/index'
  get 'jobs/show'
  get 'jobs/new'
  get 'jobs/create'
  get 'jobs/edit'
  get 'jobs/update'
  get 'jobs/destroy'
  get 'projects/index'
  get 'projects/show'
  get 'projects/new'
  get 'projects/create'
  get 'projects/edit'
  get 'projects/update'
  get 'projects/destroy'
  get 'companies/index'
  get 'companies/show'
  get 'companies/new'
  get 'companies/create'
  get 'companies/edit'
  get 'companies/update'
  get 'companies/destroy'
  get 'home/index'
  get 'home/show'

  root :to => "jobs#index"

  match '/index.csv' => 'jobs#index', via: :get, defaults: { format: :csv }

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations'}

  devise_scope :user do
    get "login", to: "users/sessions#new"
    authenticated :user do
      root :to => 'jobs#index', as: :authenticated_root
      get "sign_uo", to: "devise/registrastions#new"
    end
    unauthenticated :user do
      root :to => 'users/sessions#new', as: :unauthenticated_root
    end

  resources :companies
  resources :projects
  resources :jobs

  end

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :projects
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @page_title = "Kompanija"
    @companies = Company.all

    @companies_grid = initialize_grid(@companies, order: 'companies.name', order_direction: 'desc', per_page: 15)
  end

  def show
    @company = Company.find(params[:id])
    @page_title = "Kompanija | " + @company.title
  end

  def new
    @company = Company.new
    @page_title = "Kompanija | New"
  end

  def create
    @company = Company.new(company_params)

    @company.save

    flash[:notice] = "Dodana je nova kompanija!"

    redirect_to companies_index_path
  end

  def edit
    @company = Company.find(params[:id])
    @page_title = "Edit | "+@company.title
  end

  def update
    @company = Company.find(params[:id])

    @company.update(company_params)

    flash[:notice] = "Kompanija je izmijenjena!"

    redirect_to companies_index_path
  end

  def destroy
    @company = Company.find(params[:id])

    @company.destroy

    flash[:notice] = "Kompanija je izbrisana!"

    redirect_to companies_index_path
  end

  protected
  def company_params
    params.require(:company).permit(:name, :country, :city, :address, :vat)
  end
end

app/helpers/users/companies_helper.rb
module Users::CompaniesHelper
end

app/views/companies/_companies_grid.erb
<%= grid(@companies_grid, show_filters: :always) do |g|

  g.column name: 'Id', attribute: 'id', filter: false, in_csv: false do |t|
    t.id
  end

  g.column name: 'Ime', attribute: 'name' do |t|
    t.name
  end

  g.column name: 'Država', attribute: 'country', custom_filter: :auto do |t|
    t.country
  end

  g.column name: 'Grad', attribute: 'city', custom_filter: :auto do |t|
    t.city
  end

  g.column name: 'Adresa', attribute: 'address' do |t|
    t.address
  end

  g.column name: 'OIB/VAT', attribute: 'vat' do |t|
    t.vat
  end

  end -%>

app/views/companies/create.html.erb
<h1>Users::Companies#create</h1>
<p>Find me in app/views/users/companies/create.html.erb</p>

app/views/companies/destroy.html.erb
<h1>Users::Companies#destroy</h1>
<p>Find me in app/views/users/companies/destroy.html.erb</p>

app/views/companies/edit.html.erb
<div class="page-header head-page">
  <h1>Uredi Kupca</h1>
</div>

<%= simple_form_for @company, html: {class: 'form-horizontal'} do |f| %>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <%= f.input :name, label: "Naziv kupca", required: true %>
        <div class="row">
        <div class="col-md-4">
        <%= f.input :country, as: :country,:priority => ["HR"], label: "Država", required: true %>
        </div>
        <div class="col-md-4">
        <%= f.input :city, label: "Grad", required: true %>
        </div>
        <div class="col-md-4">
        <%= f.input :address, label: "Adresa", required: true %>
        </div>
        </div>
        <%= f.input :vat, label: "OIB/VAT", required: true %>

        <%= f.button :submit, "Izmijeni kupca", class: "btn btn-success" %>
        <%= link_to "Cancel", companies_index_path, class: "btn btn-default" %>
      </div>
    </div>
<% end %>

app/views/companies/index.html.erb
<div class="page-header head-page">
  <h1>Kompanije</h1>
</div>

<%= link_to "Nova Kompanija", companies_new_path, class: "btn btn-success marginBott" %>

<%= render partial: 'companies/companies_grid' %>

app/views/companies/new.html.erb
<div class="page-header head-page">
  <h1>Novi Kupac</h1>
</div>

<%= simple_form_for @company, html: {class: 'form-horizontal'} do |f| %>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
    <%= f.input :name, label: "Naziv kupca", required: true %>
        <div class="row">
          <div class="col-md-4 field_margin">
            <%= f.input :country, as: :country,:priority => ["HR"], label: "Država", required: true %>
          </div>
          <div class="col-md-4 field_margin">
            <%= f.input :city, label: "Grad", required: true %>
          </div>
          <div class="col-md-4 field_margin">
            <%= f.input :address, label: "Adresa", required: true %>
          </div>
        </div>
    <%= f.input :vat, label: "OIB/VAT", required: true %>

    <%= f.button :submit, "Kreiraj kupca", class: "btn btn-success" %>
    <%= link_to "Cancel", companies_index_path, class: "btn btn-default" %>
      </div>
    </div>
<% end %>

app/views/companies/update.html.erb
<h1>Users::Companies#update</h1>
<p>Find me in app/views/users/companies/update.html.erb</p>