config/routes.rb
Rails.application.routes.draw do

  get 'jobs/index'
  get 'jobs/show'
  get 'jobs/new'
  get 'jobs/create'
  get 'jobs/edit'
  get 'jobs/update'
  get 'jobs/destroy'
  get 'projects/index'
  get 'projects/show'
  get 'projects/new'
  get 'projects/create'
  get 'projects/edit'
  get 'projects/update'
  get 'projects/destroy'
  get 'companies/index'
  get 'companies/show'
  get 'companies/new'
  get 'companies/create'
  get 'companies/edit'
  get 'companies/update'
  get 'companies/destroy'
  get 'home/index'
  get 'home/show'

  root :to => "jobs#index"

  match '/index.csv' => 'jobs#index', via: :get, defaults: { format: :csv }

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations'}

  devise_scope :user do
    get "login", to: "users/sessions#new"
    authenticated :user do
      root :to => 'jobs#index', as: :authenticated_root
      get "sign_uo", to: "devise/registrastions#new"
    end
    unauthenticated :user do
      root :to => 'users/sessions#new', as: :unauthenticated_root
    end

  resources :companies
  resources :projects
  resources :jobs

  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <title> CC | <%= @page_title ? @page_title : 'TT' %></title>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">


  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand my-brand" href="#">Cactus Code</a>

    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse js--msr" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav ">
      </ul>


      <div class="nav navbar-nav navbar-left js--msr" >
        <a class="menu-slide-left js--msr-icon" id="menu-toggle" ><i class="ion-navicon-round"></i> </a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>

      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->

</nav>


<div id="wrapper" class="toggled">

  <!-- Sidebar -->
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand">
        <a href="#" methods="get">

        </a>
      </li>
      <li class="<%= params[:controller] == 'jobs' ? 'selected-menu' : '' %>">
        <%= link_to "Vremenska lista", jobs_index_path %>
      </li>
      <li class="<%= params[:controller] == 'projects' ? 'selected-menu' : '' %>">
        <%= link_to "Projekti", projects_index_path %>
      </li>
      <li class="<%= params[:controller] == 'companies' ? 'selected-menu' : '' %>">
        <%= link_to "Kompanije", companies_index_path %>
      </li>

    </ul>
  </div>
  <!-- /#sidebar-wrapper -->

  <!-- Page Content -->
  <div id="page-content-wrapper" style="padding-top: 70px;">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">

          <% if flash[:notice] %>
              <div class="alert alert-success" role="alert">
                <%= flash[:notice] %>
              </div>
          <% end %>

          <%= yield %>


        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#wrapper").toggleClass("toggled");
  });

  $(document).ready(function() {
    $('.js--msr-icon').click(function () {
      var icon = $('.js--msr-icon i');
      var nav = $('.js--msr a');

      if (icon.hasClass('ion-navicon-round')) {
        icon.addClass('ion-close-round');
        nav.addClass('menu-slide-right');
        icon.removeClass('ion-navicon-round');
        nav.removeClass('menu-slide-left');
      } else {
        icon.addClass('ion-navicon-round');
        nav.addClass('menu-slide-left');
        nav.removeClass('menu-slide-right');
        icon.removeClass('ion-close-round');
      }


    });

  });

  $(function() {
    $('.datepicker').datepicker();
  });
</script>

</body>
</html>

app/views/layouts/sign_in.erb
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Login</title>

  <%= stylesheet_link_tag    'sign_in', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8"/>

</head>
<body class="align">

<div class="site__container">

  <div class="grid__container">

    <form action="" method="post" class="form form--login">

      <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>

    </form>

  </div>

</div>
</body>
</html>